export const TIMEZONES = [
	{ timezone: 'Afghanistan/Kabul', gmt: '+04:30' },
	{ timezone: 'Åland Islands/Mariehamn', gmt: '+02:00' },
	{ timezone: 'Albania/Tirane', gmt: '+01:00' },
	{ timezone: 'Algeria/Algiers', gmt: '+01:00' },
	{ timezone: 'Andorra/Andorra', gmt: '+01:00' },
	{ timezone: 'Angola/Luanda', gmt: '+01:00' },
	{ timezone: 'Anguilla/Anguilla', gmt: '-04:00' },
	{ timezone: 'Antarctica/Rothera', gmt: '-03:00' },
	{ timezone: 'Antarctica/Troll', gmt: '+00:00' },
	{ timezone: 'Antarctica/Syowa', gmt: '+03:00' },
	{ timezone: 'Antarctica/Mawson/Vostok', gmt: '+05:00' },
	{ timezone: 'Antarctica/Davis', gmt: '+07:00' },
	{ timezone: 'Antarctica/Casey', gmt: '+08:00' },
	{ timezone: `Antarctica/Dumont d'Urville`, gmt: '+10:00' },
	{ timezone: 'Antarctica/McMurdo', gmt: '+13:00' },
	{ timezone: `Antigua and Barbuda/St. John's`, gmt: '-04:00' },
	{ timezone: 'Argentina/Buenos Aires', gmt: '-03:00' },
	{ timezone: 'Armenia/Yerevan', gmt: '+04:00' },
	{ timezone: 'Aruba/Oranjestad', gmt: '-04:00' },
	{ timezone: 'Australia/Perth', gmt: '+08:00' },
	{ timezone: 'Australia/Eucla', gmt: '+08:45' },
	{ timezone: 'Australia/Darwin', gmt: '+09:30' },
	{ timezone: 'Australia/Brisbane', gmt: '+10:00' },
	{ timezone: 'Australia/Adelaide', gmt: '+10:30' },
	{ timezone: 'Australia/Canberra/Sydney', gmt: '+11:00' },
	{ timezone: 'Austria/Vienna', gmt: '+01:00' },
	{ timezone: 'Azerbaijan/Baku', gmt: '+04:00' },
	{ timezone: 'Bahamas/Nassau', gmt: '-05:00' },
	{ timezone: 'Bahrain/Manama', gmt: '+03:00' },
	{ timezone: 'Bangladesh/Dhaka', gmt: '+06:00' },
	{ timezone: 'Barbados/Bridgetown', gmt: '-04:00' },
	{ timezone: 'Belarus/Minsk', gmt: '+03:00' },
	{ timezone: 'Belgium/Brussels', gmt: '+01:00' },
	{ timezone: 'Belize/Belmopan', gmt: '-06:00' },
	{ timezone: 'Benin/Porto Novo', gmt: '+01:00' },
	{ timezone: 'Bermuda/Hamilton', gmt: '-04:00' },
	{ timezone: 'Bhutan/Thimphu', gmt: '+06:00' },
	{ timezone: 'Bolivia/La Paz/Sucre', gmt: '-04:00' },
	{ timezone: 'Bonaire/Kralendijk', gmt: '-04:00' },
	{ timezone: 'Bosnia and Herzegovina/Sarajevo', gmt: '+01:00' },
	{ timezone: 'Botswana/Gaborone', gmt: '+02:00' },
	{ timezone: 'Brazil/Rio Branco', gmt: '-05:00' },
	{ timezone: 'Brazil/Manaus', gmt: '-04:00' },
	{ timezone: 'Brazil/Brasilia/Sao Paulo', gmt: '-03:00' },
	{ timezone: 'Brazil/Noronha', gmt: '-02:00' },
	{ timezone: 'British Indian Ocean Territory/Chagos', gmt: '+06:00' },
	{ timezone: 'Brunei/Bandar Seri Begawan', gmt: '+08:00' },
	{ timezone: 'Bulgaria/Sofia', gmt: '+02:00' },
	{ timezone: 'Burkina Faso/Ouagadougou', gmt: '+00:00' },
	{ timezone: 'Burundi/Gitega', gmt: '+02:00' },
	{ timezone: 'Cabo Verde/Praia', gmt: '-01:00' },
	{ timezone: 'Cambodia/Phnom Penh', gmt: '+07:00' },
	{ timezone: 'Cameroon/Yaounde', gmt: '+01:00' },
	{ timezone: 'Canada/Vancouver', gmt: '-08:00' },
	{ timezone: 'Canada/Edmonton', gmt: '-07:00' },
	{ timezone: 'Canada/Winnipeg', gmt: '-06:00' },
	{ timezone: 'Canada/Ottawa/Toronto', gmt: '-05:00' },
	{ timezone: 'Canada/Halifax', gmt: '-04:00' },
	{ timezone: 'Canada/St. Johns', gmt: '-03:30' },
	{ timezone: 'Cape Verde/Praia', gmt: '-01:00' },
	{ timezone: 'Cayman Islands/Cayman', gmt: '-05:00' },
	{ timezone: 'Central African Republic/Bangui', gmt: '+01:00' },
	{ timezone: 'Chad/Ndjamena', gmt: '+01:00' },
	{ timezone: 'Chile/Easter', gmt: '-05:00' },
	{ timezone: 'Chile/Santiago', gmt: '-03:00' },
	{ timezone: 'China/Urumqi', gmt: '+06:00' },
	{ timezone: 'China/Beijing/Shanghai', gmt: '+08:00' },
	{ timezone: 'Christmas Island/Christmas', gmt: '+07:00' },
	{ timezone: 'Cocos (Keeling) Islands/Cocos', gmt: '+06:30' },
	{ timezone: 'Colombia/Bogota', gmt: '-05:00' },
	{ timezone: 'Comoros/Moroni', gmt: '+03:00' },
	{ timezone: 'Cook Islands/Rarotonga', gmt: '-10:00' },
	{ timezone: 'Costa Rica/San José', gmt: '-06:00' },
	{ timezone: `Côte d'Ivoire/Yamoussoukro`, gmt: '+00:00' },
	{ timezone: 'Croatia/Zagreb', gmt: '+01:00' },
	{ timezone: 'Cuba/Havana', gmt: '-05:00' },
	{ timezone: 'Curaçao/Curacao', gmt: '-04:00' },
	{ timezone: 'Cyprus/Nicosia', gmt: '+02:00' },
	{ timezone: 'Czech Republic/Prague', gmt: '+01:00' },
	{ timezone: 'Democratic Republic of the Congo/Kinshasa', gmt: '+01:00' },
	{ timezone: 'Democratic Republic of the Congo/Lubumbashi', gmt: '+02:00' },
	{ timezone: 'Denmark/Copenhagen', gmt: '+01:00' },
	{ timezone: 'Djibouti/Djibouti', gmt: '+03:00' },
	{ timezone: 'Dominica/Roseau', gmt: '-04:00' },
	{ timezone: 'Dominican Republic/Santo Domingo', gmt: '-04:00' },
	{ timezone: 'East Timor/Dili', gmt: '+09:00' },
	{ timezone: 'Ecuador/Galapagos', gmt: '-06:00' },
	{ timezone: 'Ecuador/Quito', gmt: '-05:00' },
	{ timezone: 'Egypt/Cairo', gmt: '+02:00' },
	{ timezone: 'El Salvador/San Salvador', gmt: '-06:00' },
	{ timezone: 'Equatorial Guinea/Malabo', gmt: '+01:00' },
	{ timezone: 'Eritrea/Asmara', gmt: '+03:00' },
	{ timezone: 'Estonia/Tallinn', gmt: '+02:00' },
	{ timezone: 'Eswatini/Mbabane ', gmt: '+02:00' },
	{ timezone: 'Ethiopia/Addis Ababa', gmt: '+03:00' },
	{ timezone: 'Falkland Islands (Malvinas)/Stanley', gmt: '-03:00' },
	{ timezone: 'Faroe Islands/Faroe', gmt: '+00:00' },
	{ timezone: 'Fiji/Suva', gmt: '+12:00' },
	{ timezone: 'Finland/Helsinki', gmt: '+02:00' },
	{ timezone: 'France/Paris', gmt: '+01:00' },
	{ timezone: 'French Guiana/Cayenne', gmt: '-03:00' },
	{ timezone: 'French Polynesia/Tahiti', gmt: '-10:00' },
	{ timezone: 'French Southern Territories/Kerguelen', gmt: '+05:00' },
	{ timezone: 'Gabon/Libreville', gmt: '+01:00' },
	{ timezone: 'Gambia/Banjul', gmt: '+00:00' },
	{ timezone: 'Georgia/Tbilisi', gmt: '+04:00' },
	{ timezone: 'Germany/Berlin', gmt: '+01:00' },
	{ timezone: 'Ghana/Accra', gmt: '+00:00' },
	{ timezone: 'Gibraltar/Gibraltar', gmt: '+01:00' },
	{ timezone: 'Greece/Athens', gmt: '+02:00' },
	{ timezone: 'Greenland/Thule', gmt: '-04:00' },
	{ timezone: 'Greenland/Nuuk', gmt: '-02:00' },
	{ timezone: 'Greenland/Danmarkshavn', gmt: '+00:00' },
	{ timezone: `Grenada/St. George's`, gmt: '-04:00' },
	{ timezone: 'Guadeloupe/Basse-Terre', gmt: '-04:00' },
	{ timezone: 'Guam/Hagåtña', gmt: '+10:00' },
	{ timezone: 'Guatemala/Guatemala City', gmt: '-06:00' },
	{ timezone: 'Guernsey/Saint Peter Port', gmt: '+00:00' },
	{ timezone: 'Guinea/Conakry', gmt: '+00:00' },
	{ timezone: 'Guinea-Bissau/Bissau', gmt: '+00:00' },
	{ timezone: 'Guyana/Georgetown', gmt: '-04:00' },
	{ timezone: 'Haiti/Port-au-Prince', gmt: '-05:00' },
	{ timezone: 'Holy See/Vatican', gmt: '+01:00' },
	{ timezone: 'Honduras/Tegucigalpa', gmt: '-06:00' },
	{ timezone: 'Hong Kong/Hong Kong', gmt: '+08:00' },
	{ timezone: 'Hungary/Budapest', gmt: '+01:00' },
	{ timezone: 'Iceland/Reykjavik', gmt: '+00:00' },
	{ timezone: 'India/New Delhi', gmt: '+05:30' },
	{ timezone: 'Indonesia/Jakarta', gmt: '+07:00' },
	{ timezone: 'Indonesia/Makassar', gmt: '+08:00' },
	{ timezone: 'Indonesia/Jayapura', gmt: '+09:00' },
	{ timezone: 'Iran/Tehran', gmt: '+03:30' },
	{ timezone: 'Iraq/Baghdad', gmt: '+03:00' },
	{ timezone: 'Ireland/Dublin', gmt: '+00:00' },
	{ timezone: 'Isle of Man/Douglas', gmt: '+00:00' },
	{ timezone: 'Israel/Jerusalem', gmt: '+02:00' },
	{ timezone: 'Italy/Rome', gmt: '+01:00' },
	{ timezone: 'Jamaica/Kingston', gmt: '-05:00' },
	{ timezone: 'Japan/Tokyo', gmt: '+09:00' },
	{ timezone: 'Jersey/Saint Helier', gmt: '+00:00' },
	{ timezone: 'Jordan/Amman', gmt: '+03:00' },
	{ timezone: 'Kazakhstan/Astana', gmt: '+05:00' },
	{ timezone: 'Kenya/Nairobi', gmt: '+03:00' },
	{ timezone: 'Kiribati/Tarawa', gmt: '+12:00' },
	{ timezone: 'Kiribati/Kanton', gmt: '+13:00' },
	{ timezone: 'Kiribati/Kiritimati', gmt: '+14:00' },
	{ timezone: 'Kosovo/Pristina', gmt: '+01:00' },
	{ timezone: 'Kuwait/Kuwait City', gmt: '+03:00' },
	{ timezone: 'Kyrgyzstan/Bishkek', gmt: '+06:00' },
	{ timezone: 'Laos/Vientiane', gmt: '+07:00' },
	{ timezone: 'Latvia/Riga', gmt: '+02:00' },
	{ timezone: 'Lebanon/Beirut', gmt: '+02:00' },
	{ timezone: 'Lesotho/Maseru', gmt: '+02:00' },
	{ timezone: 'Liberia/Monrovia', gmt: '+00:00' },
	{ timezone: 'Libya/Tripoli', gmt: '+02:00' },
	{ timezone: 'Liechtenstein/Vaduz', gmt: '+01:00' },
	{ timezone: 'Lithuania/Vilnius', gmt: '+02:00' },
	{ timezone: 'Luxembourg/Luxembourg City', gmt: '+01:00' },
	{ timezone: 'Macao/Macau', gmt: '+08:00' },
	{ timezone: 'Macedonia/Skopje', gmt: '+01:00' },
	{ timezone: 'Madagascar/Antananarivo', gmt: '+03:00' },
	{ timezone: 'Malawi/Lilongwe', gmt: '+02:00' },
	{ timezone: 'Malaysia/Kuala Lumpur', gmt: '+08:00' },
	{ timezone: 'Maldives/Malé', gmt: '+05:00' },
	{ timezone: 'Mali/Bamako', gmt: '+00:00' },
	{ timezone: 'Malta/Valletta', gmt: '+01:00' },
	{ timezone: 'Marshall Islands/Majuro', gmt: '+12:00' },
	{ timezone: 'Martinique/Fort-de-France', gmt: '-04:00' },
	{ timezone: 'Mauritania/Nouakchott', gmt: '+00:00' },
	{ timezone: 'Mauritius/Port Louis', gmt: '+04:00' },
	{ timezone: 'Mayotte/Mamoudzou', gmt: '+03:00' },
	{ timezone: 'Mexico/Tijuana', gmt: '-08:00' },
	{ timezone: 'Mexico/Ciudad Juarez', gmt: '-07:00' },
	{ timezone: 'Mexico/Mexico City', gmt: '-06:00' },
	{ timezone: 'Mexico/Cancun', gmt: '-05:00' },
	{ timezone: 'Micronesia/Chuuk', gmt: '+10:00' },
	{ timezone: 'Micronesia/Palikir', gmt: '+11:00' },
	{ timezone: 'Moldova/Chisinau', gmt: '+02:00' },
	{ timezone: 'Monaco/Monaco City', gmt: '+01:00' },
	{ timezone: 'Mongolia/Hovd', gmt: '+07:00' },
	{ timezone: 'Mongolia/Ulaanbaatar', gmt: '+08:00' },
	{ timezone: 'Montenegro/Podgorica', gmt: '+01:00' },
	{ timezone: 'Montserrat/Montserrat', gmt: '-04:00' },
	{ timezone: 'Morocco/Rabat', gmt: '+01:00' },
	{ timezone: 'Mozambique/Maputo', gmt: '+02:00' },
	{ timezone: 'Myanmar/Yangon', gmt: '+06:30' },
	{ timezone: 'Namibia/Windhoek', gmt: '+02:00' },
	{ timezone: 'Nauru/Yaren', gmt: '+12:00' },
	{ timezone: 'Nepal/Kathmandu', gmt: '+05:45' },
	{ timezone: 'Netherlands/Amsterdam', gmt: '+01:00' },
	{ timezone: 'New Caledonia/Noumea', gmt: '+11:00' },
	{ timezone: 'New Zealand/Wellington', gmt: '+13:00' },
	{ timezone: 'New Zealand/Chatham', gmt: '+13:45' },
	{ timezone: 'Nicaragua/Managua', gmt: '-06:00' },
	{ timezone: 'Niger/Niamey', gmt: '+01:00' },
	{ timezone: 'Nigeria/Abuja', gmt: '+01:00' },
	{ timezone: 'Niue/Alofi', gmt: '-11:00' },
	{ timezone: 'Norfolk Island/Kingston', gmt: '+12:00' },
	{ timezone: 'North Korea/Pyongyang', gmt: '+09:00' },
	{ timezone: 'North Macedonia/Skopje', gmt: '+01:00' },
	{ timezone: 'Northern Mariana Islands/Saipan', gmt: '+10:00' },
	{ timezone: 'Norway/Oslo', gmt: '+01:00' },
	{ timezone: 'Oman/Muscat', gmt: '+04:00' },
	{ timezone: 'Pakistan/Islamabad', gmt: '+05:00' },
	{ timezone: 'Palau/Ngerulmud', gmt: '+09:00' },
	{ timezone: 'Palestine/Hebron', gmt: '+02:00' },
	{ timezone: 'Panama/Panama City', gmt: '-05:00' },
	{ timezone: 'Papua New Guinea/Bougainville', gmt: '+11:00' },
	{ timezone: 'Papua New Guinea/Port Moresby', gmt: '+10:00' },
	{ timezone: 'Paraguay/Asuncion', gmt: '-03:00' },
	{ timezone: 'Peru/Lima', gmt: '-05:00' },
	{ timezone: 'Philippines/Manila', gmt: '+08:00' },
	{ timezone: 'Pitcairn/Adamstown', gmt: '-08:00' },
	{ timezone: 'Poland/Warsaw', gmt: '+01:00' },
	{ timezone: 'Portugal/Azores', gmt: '-01:00' },
	{ timezone: 'Portugal/Lisbon', gmt: '+00:00' },
	{ timezone: 'Puerto Rico/San Juan', gmt: '-04:00' },
	{ timezone: 'Qatar/Doha', gmt: '+03:00' },
	{ timezone: 'Republic of the Congo/Brazzaville', gmt: '+01:00' },
	{ timezone: 'Romania/Bucharest', gmt: '+02:00' },
	{ timezone: 'Russian Federation/Kaliningrad', gmt: '+02:00' },
	{ timezone: 'Russian Federation/Moscow', gmt: '+03:00' },
	{ timezone: 'Russian Federation/Samara', gmt: '+04:00' },
	{ timezone: 'Russian Federation/Yekaterinburg', gmt: '+05:00' },
	{ timezone: 'Russian Federation/Omsk', gmt: '+06:00' },
	{ timezone: 'Russian Federation/Novosibirsk', gmt: '+07:00' },
	{ timezone: 'Russian Federation/Irkutsk', gmt: '+08:00' },
	{ timezone: 'Russian Federation/Yakutsk', gmt: '+09:00' },
	{ timezone: 'Russian Federation/Vladivostok', gmt: '+10:00' },
	{ timezone: 'Russian Federation/Magadan', gmt: '+11:00' },
	{ timezone: 'Russian Federation/Kamchatka', gmt: '+12:00' },
	{ timezone: 'Rwanda/Kigali', gmt: '+02:00' },
	{ timezone: 'Réunion/Saint-Denis', gmt: '+04:00' },
	{ timezone: 'Saint Barthélemy/St. Barthelemy', gmt: '-04:00' },
	{ timezone: 'Saint Helena/St. Helena', gmt: '+00:00' },
	{ timezone: 'Saint Kitts and Nevis/Basseterre', gmt: '-04:00' },
	{ timezone: 'Saint Lucia/Castries', gmt: '-04:00' },
	{ timezone: 'Saint Martin/Marigot', gmt: '-04:00' },
	{ timezone: 'Saint Pierre and Miquelon/Miquelon', gmt: '-03:00' },
	{ timezone: 'Saint Vincent and the Grenadines/Kingstown', gmt: '-04:00' },
	{ timezone: 'Samoa/Apia', gmt: '+13:00' },
	{ timezone: 'San Marino/City of San Marino', gmt: '+01:00' },
	{ timezone: 'Sao Tome and Principe/Sao Tome', gmt: '+03:00' },
	{ timezone: 'Saudi Arabia/Riyadh', gmt: '+00:00' },
	{ timezone: 'Senegal/Dakar', gmt: '+00:00' },
	{ timezone: 'Serbia/Belgrade', gmt: '+01:00' },
	{ timezone: 'Seychelles/Victoria', gmt: '+04:00' },
	{ timezone: 'Sierra Leone/Freetown', gmt: '+00:00' },
	{ timezone: 'Singapore/Singapore', gmt: '+08:00' },
	{ timezone: 'Sint Maarten/Lower Princes', gmt: '-04:00' },
	{ timezone: 'Slovakia/Bratislava', gmt: '+01:00' },
	{ timezone: 'Slovenia/Ljubljana', gmt: '+01:00' },
	{ timezone: 'Solomon Islands/Honiara', gmt: '+11:00' },
	{ timezone: 'Somalia/Mogadishu', gmt: '+03:00' },
	{ timezone: 'South Africa/Pretoria', gmt: '+02:00' },
	{ timezone: 'South Georgia/South Georgia', gmt: '-02:00' },
	{ timezone: 'South Korea/Seoul', gmt: '+09:00' },
	{ timezone: 'South Sudan/Juba', gmt: '+02:00' },
	{ timezone: 'Spain/Canary', gmt: '+00:00' },
	{ timezone: 'Spain/Madrid', gmt: '+01:00' },
	{ timezone: 'Sri Lanka/Sri Jayawardenepura Kotte', gmt: '+05:30' },
	{ timezone: 'Sudan/Khartoum', gmt: '+02:00' },
	{ timezone: 'Suriname/Paramaribo', gmt: '-03:00' },
	{ timezone: 'Svalbard and Jan Mayen/Longyearbyen', gmt: '+01:00' },
	{ timezone: 'Swaziland/Mbabane', gmt: '+02:00' },
	{ timezone: 'Sweden/Stockholm', gmt: '+01:00' },
	{ timezone: 'Switzerland/Bern', gmt: '+01:00' },
	{ timezone: 'Syria/Damascus', gmt: '+03:00' },
	{ timezone: 'Taiwan/Taipei', gmt: '+08:00' },
	{ timezone: 'Tajikistan/Dushanbe', gmt: '+05:00' },
	{ timezone: 'Tanzania/Dodoma', gmt: '+03:00' },
	{ timezone: 'Thailand/Bangkok', gmt: '+07:00' },
	{ timezone: 'Timor-Leste/Dili', gmt: '+09:00' },
	{ timezone: 'Togo/Lome', gmt: '+00:00' },
	{ timezone: 'Tokelau/Fakaofo', gmt: '+13:00' },
	{ timezone: `Tonga/Nuku'alofa`, gmt: '+13:00' },
	{ timezone: 'Trinidad and Tobago/Port of Spain', gmt: '-04:00' },
	{ timezone: 'Tunisia/Tunis', gmt: '+01:00' },
	{ timezone: 'Turkey/Ankara', gmt: '+03:00' },
	{ timezone: 'Turkmenistan/Ashgabat', gmt: '+05:00' },
	{ timezone: 'Turks and Caicos Islands/Grand Turk', gmt: '-05:00' },
	{ timezone: 'Tuvalu/Funafuti', gmt: '+12:00' },
	{ timezone: 'Uganda/Kampala', gmt: '+03:00' },
	{ timezone: 'Ukraine/Kyiv', gmt: '+02:00' },
	{ timezone: 'Ukraine/Simferopol', gmt: '+03:00' },
	{ timezone: 'United Arab Emirates/Abu Dhabi', gmt: '+04:00' },
	{ timezone: 'United Kingdom/London', gmt: '+00:00' },
	{ timezone: 'USA/American Samoa', gmt: '-11:00' },
	{ timezone: 'USA/Honolulu', gmt: '-10:00' },
	{ timezone: 'USA/Anchorage', gmt: '-09:00' },
	{ timezone: 'USA/Los Angeles', gmt: '-08:00' },
	{ timezone: 'USA/Denver', gmt: '-07:00' },
	{ timezone: 'USA/Chicago', gmt: '-06:00' },
	{ timezone: 'USA/Washington D.C./New York', gmt: '-05:00' },
	{ timezone: 'USA/Wake', gmt: '+12:00' },
	{ timezone: 'Uruguay/Montevideo', gmt: '-03:00' },
	{ timezone: 'Uzbekistan/Tashkent', gmt: '+05:00' },
	{ timezone: 'Vanuatu/Port Vila', gmt: '+11:00' },
	{ timezone: 'Vatican City/Vatican City', gmt: '+01:00' },
	{ timezone: 'Venezuela/Caracas', gmt: '-04:00' },
	{ timezone: 'VietNam/Hanoi', gmt: '+07:00' },
	{ timezone: 'Virgin Islands/St. Thomas', gmt: '-04:00' },
	{ timezone: 'Wallis and Futuna/Wallis', gmt: '+12:00' },
	{ timezone: `Yemen/Sana'a`, gmt: '+03:00' },
	{ timezone: 'Zambia/Lusaka', gmt: '+02:00' },
	{ timezone: 'Zimbabwe/Harare', gmt: '+02:00' },
];
